version: '3.3'
  
services:

  dbrtg:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_rtg_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
      
  web:
    image: readytogo:latest
    restart: always
    volumes:
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
      - dbrtg
    env_file:
      - ../.env
      
  nginx:
    image: nginx:1.19.3
    restart: always
    ports: # в конфиге серверного nginx настроить proxy_pass на порты, которые слушает контейнер (8085 и 8083)
      - 8085:80
      - 8083:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  postgres_rtg_data:
  static_value:
  media_value: