# Generated by Django 3.0.5 on 2022-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название гонки')),
                ('slug', models.SlugField(max_length=70)),
                ('date', models.DateField()),
                ('cup', models.TextField(max_length=50)),
                ('town', models.TextField(max_length=50)),
                ('start_numbers', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=150)),
            ],
            options={
                'unique_together': {('slug', 'date')},
            },
        ),
    ]
