# Generated by Django 3.0.5 on 2022-03-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rases',
            new_name='Races',
        ),
    ]
