# Generated by Django 3.0.5 on 2022-03-07 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20220308_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='races',
            name='start_numbers',
        ),
        migrations.AddField(
            model_name='races',
            name='numbers_amount',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не меньше 1')]),
            preserve_default=False,
        ),
    ]
