# Generated by Django 3.0.5 on 2022-03-09 18:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20220308_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=70)),
                ('year_old', models.IntegerField(validators=[django.core.validators.MinValueValidator(1940, message='Не старше 1940 г.р.')])),
                ('year_yang', models.IntegerField(validators=[django.core.validators.MinValueValidator(1940, message='Не старше 1940 г.р.')])),
                ('number_start', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не меньше 1')])),
                ('number_end', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не меньше 1')])),
                ('description', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Кубка')),
                ('slug', models.SlugField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='races',
            name='numbers_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не меньше 1')]),
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1940, message='Не старше 1940 г.р.')], verbose_name='Год рождения')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не меньше 1')], verbose_name='Стартовый номер')),
                ('club', models.CharField(max_length=50, null=True, verbose_name='Принадлежность к клубу')),
                ('town', models.CharField(max_length=50, null=True, verbose_name='Из какого города?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_participants', to='registration.Categories')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_participants', to='registration.Races')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_categories', to='registration.Races'),
        ),
        migrations.AlterField(
            model_name='races',
            name='cup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup_races', to='registration.Cups'),
        ),
    ]
