# Generated by Django 3.0.5 on 2022-03-14 18:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20220309_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='number_end',
            field=models.IntegerField(blank=True, null=b'I01\n', validators=[django.core.validators.MinValueValidator(1, message='Значение не меньше 1')]),
        ),
        migrations.AlterField(
            model_name='categories',
            name='number_start',
            field=models.IntegerField(blank=True, null=b'I01\n', validators=[django.core.validators.MinValueValidator(1, message='Значение не меньше 1')]),
        ),
        migrations.AlterField(
            model_name='cups',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_participants', to='registration.Categories', verbose_name='Категория участника'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='club',
            field=models.CharField(blank=True, max_length=50, null=b'I01\n', verbose_name='Принадлежность к клубу'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=b'I01\n', verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_participants', to='registration.Races', verbose_name='Название гонки'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=b'I01\n', verbose_name='Из какого города?'),
        ),
        migrations.AlterField(
            model_name='races',
            name='cup',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='cup_races', to='registration.Cups'),
        ),
        migrations.AlterField(
            model_name='races',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=b'I01\n'),
        ),
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together={('race', 'name', 'surname', 'patronymic')},
        ),
    ]
