# Generated by Django 3.0.5 on 2022-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20220314_2354'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('race', 'name', 'surname', 'patronymic'), name='race_member'),
        ),
    ]
