# Generated by Django 3.0.5 on 2022-03-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20220315_0055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participants',
            name='race_member',
        ),
        migrations.AlterField(
            model_name='participants',
            name='patronymic',
            field=models.CharField(blank=True, default='-', max_length=30, verbose_name='Отчество'),
        ),
    ]
