# Generated by Django 3.0.5 on 2022-05-02 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20220315_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='регистрация активна'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='number_end',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не меньше 1')]),
        ),
        migrations.AlterField(
            model_name='categories',
            name='number_start',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не меньше 1')]),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, default='autoslug', max_length=70),
        ),
        migrations.AlterField(
            model_name='cups',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cups',
            name='slug',
            field=models.SlugField(blank=True, default='autoslug', max_length=70),
        ),
        migrations.AlterField(
            model_name='participants',
            name='club',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Принадлежность к клубу'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Из какого города?'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='year',
            field=models.IntegerField(default=1940, validators=[django.core.validators.MinValueValidator(1940, message='Не старше 1940 г.р.')], verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='races',
            name='cup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup_races', to='registration.Cups'),
        ),
        migrations.AlterField(
            model_name='races',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='slug',
            field=models.SlugField(blank=True, default='autoslug', max_length=70),
        ),
    ]
