# Generated by Django 3.0.5 on 2022-06-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20220503_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='club',
            field=models.CharField(blank=True, default='-', max_length=50, verbose_name='Принадлежность к клубу'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='town',
            field=models.CharField(blank=True, default='-', max_length=50, verbose_name='Из какого города?'),
        ),
        migrations.AlterField(
            model_name='races',
            name='cup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup_races', to='registration.Cups', verbose_name='Группа гонок'),
        ),
    ]
