# Generated by Django 3.0.5 on 2022-10-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20220603_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='reg_code',
            field=models.CharField(default='qwerty', max_length=50, verbose_name='Код регистрации'),
            preserve_default=False,
        ),
    ]
