# Generated by Django 3.0.5 on 2022-10-31 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_participants_reg_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cups',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название Кубка'),
        ),
        migrations.AlterField(
            model_name='cups',
            name='slug',
            field=models.SlugField(default='autoslug', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='category',
            field=models.ForeignKey(on_delete=registration.models.set_def_category, related_name='category_participants', to='registration.Categories', verbose_name='Категория участника'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='race_participants', to='registration.Races', verbose_name='Название гонки'),
        ),
        migrations.AlterField(
            model_name='races',
            name='cup',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cup_races', to='registration.Cups', verbose_name='Группа гонок'),
        ),
        migrations.AlterField(
            model_name='races',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='races',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='races',
            name='numbers_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не меньше 1')], verbose_name='Количество стартовых номеров'),
        ),
        migrations.AlterField(
            model_name='races',
            name='town',
            field=models.CharField(max_length=50, verbose_name='Название города'),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('slug', 'race')},
        ),
    ]
