# Generated by Django 3.0.5 on 2022-10-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20221031_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_participants', to='registration.Categories', verbose_name='Категория участника'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_participants', to='registration.Races', verbose_name='Название гонки'),
        ),
    ]
