# Generated by Django 3.0.5 on 2023-01-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0012_auto_20221031_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='cups',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_cups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participants',
            name='category',
            field=models.ForeignKey(null=True, on_delete=registration.models.set_def_category, related_name='category_participants', to='registration.Categories', verbose_name='Категория участника'),
        ),
    ]
