# Generated by Django 3.0.5 on 2023-01-09 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0013_auto_20230106_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_races', to=settings.AUTH_USER_MODEL),
        ),
    ]
