# Generated by Django 3.0.5 on 2023-01-27 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0014_races_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
